### PR TITLE
Fixed WorldGuard 6 and 7 compat in pom

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
_This PR **only** fixes the POM, not any of the java files!_
For #28 
So, basically, this is it.
If you want, you can change the WorldGuard dependency to version 7.0.0, which the offical release, but I would stay with SNAPSHOT 7.0.1.
The exclusion is to prevent a second Worldguard dependency in the tree.

### CODE REVIEW

**Comment by UtechtDustin** [comment]
@ThexXTURBOXx 
Still the same issue, with your code the IDE/Maven now the (old) method "canBuild" but dont know the new methods(new parameters of the methods).
As example he dont know `Flags.BUILD`.
Bildschirmfoto vom 2019-07-07 16-22-44

**Comment by ThexXTURBOXx** [comment]
That isn't possible as you would load 2 different Flags-classes at runtime, which isn't possible, so the compiler gets confused.
You have to use reflection then:
```
Field f = Flags.class.getField("BUILD");
f.setAccessible(true);
StateFlag build_flag = f.get(null);
//Do something with build_flag
```

**Comment by UtechtDustin** [comment]
There is no other way to tell the compile use that flag but also ONLY check other libs ?
I love Java.. >.<

**Comment by ThexXTURBOXx** [comment]
The class "Flags" is in WorldGuard 6 and in WorldGuard 7.
In WorldGuard 6, the class doesn't contain the "BUILD" field, in 7, it does.
This behavior is not only visible in Java, but in, well, every programming language.

**Comment by UtechtDustin** [comment]
I dont know how to use reflection, for the `incompatible types` error.

**Comment by ThexXTURBOXx** [comment]
You just need to cast the value:
```
Field f = Flags.class.getField("BUILD");
f.setAccessible(true);
StateFlag build_flag = (StateFlag) f.get(null);
//Do something with build_flag
```
It's really not that hard

**Comment by UtechtDustin** [comment]
The code for the flags works, but there are some more issues.
e.g.
`!WorldGuard.getInstance().getPlatform().getSessionManager().hasBypass(WorldGuardPlugin.inst().wrapPlayer(player), world)`
In on of the version the paramter was changed...

**Comment by ThexXTURBOXx** [comment]
Like that?
```
Method m = SessionManager.class.getMethod("hasBypass", LocalPlayer.class, com.sk89q.worldedit.world.World.class);
				m.setAccessible(true);
				boolean b = (boolean) m.invoke(WorldGuard.getInstance().getPlatform().getSessionManager(), WorldGuardPlugin.inst().wrapPlayer(player), world);
//Do something with b
```

**Comment by ThexXTURBOXx** [comment]
I am by the way not sure, why the plugin should be compatible with WorldGuard 6.x as WorldGuard 7.x has a stable release now and every server should upgrade to that (they should have upgraded a long time ago normally...)

**Comment by UtechtDustin** [comment]
Is Worlguard V7 Workinv on any Version ? (1.8.X)

**Comment by ThexXTURBOXx** [comment]
Afaik, there were some builds in the past, but I am not sure

**Comment by UtechtDustin** [comment]
I will check that, if 7 is working on 1.8+, support only 7 is okay.

**Comment by UtechtDustin** [comment]
Worldguard 7 is 1.13/1.14+ only (https://dev.bukkit.org/projects/worldguard/files).

I also cant figure out the reflection thing...
As example maven will still check if the parameter has the right type.

After reflection
```
Error:(600,101) java: method getMethod in class java.lang.Class<T> cannot be applied to given types;
```
